spring.application.name=nepheal-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/nephealll
spring.datasource.username=postgres
spring.datasource.password=Suman252
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API Logging
logging.level.org.springframework.web=INFO
logging.level.com.nepheal=DEBUG
